prog:main.c menu.c
	gcc menu.c -o image -lSDL -lSDL_image
	gcc main.c -o image -lSDL -lSDL_image 
	./image 

	gcc main.c -o texte -lSDL -lSDL_image -lSDL _ttf 
	./texte

	gcc main.c -o son -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
